### ISSUE TITLE
Massive Update Problem with Fields Plugin on Some Categories

### ISSUE THREAD

**Issue by atb42** [pluginsGLPI/fields#414]
Hi, after upgrade i have a problem on massive update when y try to make this action.

Fatal error: Uncaught Error: Class 'PluginFieldsMonitorcomputer' not found in /srv/www/htdocs/glpi/plugins/fields/inc/field.class.php:603 Stack trace: #0 /srv/www/htdocs/glpi/plugins/fields/inc/field.class.php(868): PluginFieldsField::prepareHtmlFields() #1 /srv/www/htdocs/glpi/plugins/fields/hook.php(199): PluginFieldsField::showSingle() #2 /srv/www/htdocs/glpi/inc/plugin.class.php(1196): plugin_fields_MassiveActionsFieldsDisplay() #3 /srv/www/htdocs/glpi/inc/massiveaction.class.php(859): Plugin::doOneHook() #4 /srv/www/htdocs/glpi/inc/massiveaction.class.php(619): MassiveAction::showMassiveActionsSubForm() #5 /srv/www/htdocs/glpi/ajax/dropdownMassiveAction.php(48): MassiveAction->showSubForm() #6 {main} thrown in /srv/www/htdocs/glpi/plugins/fields/inc/field.class.php on line 603

In Computers categorie it works.

Can someone help me?

Thanks !!

**Comment by virgiliua** [comment]
Hello,

I have problem with Massive Update when I try to delete computers in GLPI because of Fields Plugin:
glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFieldsComputeraccess' not found in /var/www/html/marketplace/fields/inc/container.class.php at line 574
  Backtrace :
  inc/plugin.class.php:1368                          PluginFieldsContainer::preItemPurge()
  inc/commondbtm.class.php:1786                      Plugin::doHook()
  inc/massiveaction.class.php:1179                   CommonDBTM->delete()
  inc/massiveaction.class.php:1097                   MassiveAction::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:1076                   MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()

Any solution please?
Thank you!

**Comment by stonebuzz** [comment]
There has been no activity on this issue for some time and therefore it is considered stale

If this issue is related to a bug, please try to reproduce on latest release (GLPI and plugin). If the problem persist, feel free to open a new issue.

If it is related to a new feature, please open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).

You may also consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal support or [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.
