### ISSUE TITLE
Error with combobox on Tickets

### ISSUE THREAD

**Issue by brusilva84** [pluginsGLPI/fields#569]
I had an error today that was registered on logs like this:

PHP Warning (2): Undefined array key "status" in /var/www/html/glpi/marketplace/fields/inc/container.class.php at line 1239\n  Backtrace :\n  marketplace/fields/inc/container.class.php:1055    PluginFieldsContainer::validateValues()\n  marketplace/fields/front/container.form.php:56     PluginFieldsContainer->updateFieldsValues()\n in /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php at line 146\n  Backtrace :\n  ...onolog/Handler/AbstractProcessingHandler.php:48 Monolog\\Handler\\StreamHandler->write()\n  vendor/monolog/monolog/src/Monolog/Logger.php:328  Monolog\\Handler\\AbstractProcessingHandler->handle()\n  vendor/monolog/monolog/src/Monolog/Logger.php:501  Monolog\\Logger->addRecord()\n  src/Application/ErrorHandler.php:478               Monolog\\Logger->log()\n  src/Application/ErrorHandler.php:280               Glpi\\Application\\ErrorHandler->logErrorMessage()\n  marketplace/fields/inc/container.class.php:1239    Glpi\\Application\\ErrorHandler->handleError()\n  marketplace/fields/inc/container.class.php:1055    PluginFieldsContainer::validateValues()\n  marketplace/fields/front/container.form.php:56     PluginFieldsContainer->updateFieldsValues()\n in /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146\nStack trace:\n#0 /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): Monolog\\Handler\\StreamHandler->write()\n#1 /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Logger.php(328): Monolog\\Handler\\AbstractProcessingHandler->handle()\n#2 /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Logger.php(501): Monolog\\Logger->addRecord()\n#3 /var/www/html/glpi/src/Application/ErrorHandler.php(478): Monolog\\Logger->log()\n#4 /var/www/html/glpi/src/Application/ErrorHandler.php(393): Glpi\\Application\\ErrorHandler->logErrorMessage()\n#5 [internal function]: Glpi\\Application\\ErrorHandler->handleException()\n#6 {main}\n  thrown in /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 146, referer: https://**HIDDEN-DOMAIN**/front/ticket.form.php?id=18434

I solved by comenting lines 1238 to 1247 on container.class.php that were added on this commit https://github.com/pluginsGLPI/fields/commit/3dc14345532dcc561528df28fff6c9e7ee8fa15a

**Comment by brusilva84** [comment]
With latest update I had to use the same "hack" commenting out those lines

**Comment by stonebuzz** [comment]
There has been no activity on this issue for some time and therefore it is considered stale

If this issue is related to a bug, please try to reproduce on latest release (GLPI and plugin). If the problem persist, feel free to open a new issue.

If it is related to a new feature, please open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).

You may also consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal support or [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.
